/* Copyright 2021 The MathWorks, Inc. */
#ifndef SHARED_DYNAMICTESTSEQUENCE_CORE_SPEC_HPP
#define SHARED_DYNAMICTESTSEQUENCE_CORE_SPEC_HPP

#ifdef BUILDING_SHARED_DYNAMICTESTSEQUENCE_CORE
#include "package.h"


/* This header is being included by files inside this module */

# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_CLASS    DLL_EXPORT_SYM
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_FRIEND   DLL_EXPORT_SYM
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_FCN      DLL_EXPORT_SYM
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_TEMPLATE DLL_EXPORT_TEMPLATE

# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_EXTERN_C extern "C" DLL_EXPORT_SYM

# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_VAR      extern
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_VAR_DEF  DLL_EXPORT_SYM

# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT          DLL_EXPORT_SYM

#elif defined(DLL_IMPORT_SYM)

#ifdef __cplusplus
/* This file is being include by other TMW internal modules */
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_CLASS    DLL_IMPORT_SYM
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_FRIEND   DLL_IMPORT_SYM
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_FCN      DLL_IMPORT_SYM
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_TEMPLATE DLL_EXPORT_TEMPLATE

# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_EXTERN_C extern "C" DLL_IMPORT_SYM

#else
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_EXTERN_C extern DLL_IMPORT_SYM

# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_VAR      extern DLL_IMPORT_SYM

#endif

# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT          DLL_IMPORT_SYM

#else

#ifdef __cplusplus
#define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_EXTERN_C extern "C"
#else
#define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_EXTERN_C extern
#endif

# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT
# define SHARED_DYNAMICTESTSEQUENCE_CORE_EXPORT_CLASS

#endif


#endif // SHARED_DYNAMICTESTSEQUENCE_CORE_SPEC_HPP

// EOF

